apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: data
          hostPath:
            path: ./data
      containers:
        - name: app
          image: test/flaskapp
          volumeMounts:
            - mountPath: /data
              name: data
